-- CreateTable
CREATE TABLE "universities" (
    "id" TEXT NOT NULL,
    "university_id" INTEGER NOT NULL,
    "code" TEXT,
    "name" TEXT,
    "short_name" TEXT,
    "name_en" TEXT,
    "short_name_en" TEXT,
    "edrpou" TEXT,
    "registration_date" TIMESTAMP(3),
    "university_type_name" TEXT,
    "education_type" TEXT,
    "juristical_type" TEXT,
    "finansing_type" TEXT,
    "governance_type" TEXT,
    "org_prav_form" TEXT,
    "risk_rank" TEXT,
    "is_closed" BOOLEAN NOT NULL DEFAULT false,
    "close_status_type_name" TEXT,
    "close_reason" TEXT,
    "close_date" TIMESTAMP(3),
    "is_military_chair" BOOLEAN NOT NULL DEFAULT false,
    "post_index" TEXT,
    "katottg_full_name" TEXT,
    "address_street" TEXT,
    "house_number" TEXT,
    "post_index_legal" TEXT,
    "katottg_full_name_u" TEXT,
    "address_street_legal" TEXT,
    "house_number_legal" TEXT,
    "phone_number" TEXT,
    "email" TEXT,
    "web_site" TEXT,
    "rector_full_name" TEXT,
    "rector_last_name" TEXT,
    "rector_first_name" TEXT,
    "rector_middle_name" TEXT,
    "rector_full_name_gen_case" TEXT,
    "rector_position" TEXT,
    "rector_phone" TEXT,
    "rector_email" TEXT,
    "raw" JSONB,
    "synced_at" TIMESTAMP(3) NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "universities_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "universities_university_id_key" ON "universities"("university_id");
